#!/usr/bin/env python3
"""make_icons.py — rasterize Material Design "filled" SVGs into:
  - assets/icon/<name>.png   (RGBA preview, for SD-card upload)
  - src/ui/ui_icons.h        (one C header: RGB565 arrays, transparent = 0xF81F)

Icons (Apache 2.0, Material Design / Google) are rendered WHITE on transparent
so they read clearly on the dark graphite HUD/bottom bar / gear button. The
speed-limit road sign is drawn specially (red ring + white centre) since the
limit number is overlaid at runtime.

Usage:
    python make_icons.py            # renders + writes ui_icons.h + PNGs
"""
import math
import os

import cairosvg
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_HDR = os.path.join(HERE, "..", "..", "src", "ui", "ui_icons.h")
ICON_DIR = HERE

SIZE = 40          # final icon px (square)
SS = 4             # supersample factor
TRANSP = 0xF81F    # magenta = transparent

# name -> (svg file, fill RGB or None for full-color PNG override)
# "speed_limit" is generated from scratch (not from an SVG).
ICONS = {
    "turn_left":        ("turn_left.svg",        (255, 255, 255)),
    "turn_right":       ("turn_right.svg",       (255, 255, 255)),
    "turn_slight_left": ("turn_slight_left.svg", (255, 255, 255)),
    "turn_slight_right":("turn_slight_right.svg",(255, 255, 255)),
    "straight":         ("straight.svg",         (255, 255, 255)),
    "u_turn":           ("u_turn_left.svg",      (255, 255, 255)),
    "speed":            ("speed.svg",            (255, 255, 255)),  # speedometer
    "gear":             ("settings.svg",         (255, 255, 255)),  # config gear
    "speed_limit":      (None, None),  # drawn below (red ring)
}


def render_svg(path, size, fill):
    """Render an SVG to a size x size RGBA image, recoloured to `fill`."""
    png = cairosvg.svg2png(url=path, output_width=size * SS, output_height=size * SS)
    img = Image.open(__import__("io").BytesIO(png)).convert("RGBA")
    if fill is not None:
        # Replace every opaque pixel's RGB with the target fill (keep alpha).
        r, g, b = fill
        a = img.getchannel("A")
        solid = Image.new("RGBA", img.size, (r, g, b, 255))
        img = Image.merge("RGBA", (solid.getchannel("R"),
                                   solid.getchannel("G"),
                                   solid.getchannel("B"), a))
    img = img.resize((size, size), Image.LANCZOS)
    return img


def make_speed_limit(size):
    """Red-ring road sign: red disc, white centre, thin red number gap."""
    ss = size * SS
    img = Image.new("RGBA", (ss, ss), (0, 0, 0, 0))
    d = ImageDraw = __import__("PIL.ImageDraw", fromlist=["ImageDraw"]).Draw(img)
    c = ss // 2
    R = ss // 2
    # red disc
    d.ellipse([c - R, c - R, c + R, c + R], fill=(255, 0, 0, 255))
    # white centre
    inner = R * 0.78
    d.ellipse([c - inner, c - inner, c + inner, c + inner], fill=(255, 255, 255, 255))
    # thin red gap between disc edge and white centre (for the number)
    gap = R * 0.9
    d.ellipse([c - gap, c - gap, c + gap, c + gap], outline=(255, 0, 0, 255), width=ss // 32)
    return img.resize((size, size), Image.LANCZOS)


def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def to_c_rows(img, w, h):
    rows = []
    for y in range(h):
        line = []
        for x in range(w):
            r, g, b, a = img.getpixel((x, y))
            line.append("0x%04X" % (TRANSP if a < 128 else rgb565(r, g, b)))
        rows.append(", ".join(line))
    return rows


def main():
    os.makedirs(ICON_DIR, exist_ok=True)
    headers = []
    headers.append(
        "/* ui_icons.h — white-on-transparent Material icons, %dx%d RGB565.\n"
        " * Generated by assets/icon/make_icons.py (Material Design, Apache 2.0).\n"
        " * Pixels == 0xF81F (magenta) are transparent. Draw via pushSprite.\n"
        " */\n"
        "#ifndef UI_ICONS_H_\n#define UI_ICONS_H_\n\n"
        "#define UI_ICON_SIZE %d\n#define UI_ICON_TRANSP 0xF81F\n\n" % (SIZE, SIZE, SIZE)
    )

    meta = []
    for name, (svg, fill) in ICONS.items():
        if svg:
            img = render_svg(os.path.join(ICON_DIR, svg), SIZE, fill)
        else:
            img = make_speed_limit(SIZE)
        png_path = os.path.join(ICON_DIR, name + ".png")
        img.save(png_path)

        arr = "static const uint16_t UI_ICON_%s[UI_ICON_SIZE*UI_ICON_SIZE] = {\n" % name.upper()
        arr += ",\n".join("    " + r for r in to_c_rows(img, SIZE, SIZE))
        arr += "\n};\n\n"
        headers.append(arr)
        meta.append((name, SIZE, SIZE))

    # Emit a small lookup table: name + array pointer (used by ui_controls.cpp
    # to pick the right fallback when an SD PNG is missing).
    headers.append("typedef struct { const char *name; const uint16_t *px; int w, h; } UiIconDef;\n\n")
    headers.append("static const UiIconDef UI_ICONS[] = {\n")
    for name, w, h in meta:
        headers.append('    { "%s", UI_ICON_%s, %d, %d },\n' % (name, name.upper(), w, h))
    headers.append("    { nullptr, nullptr, 0, 0 }\n};\n\n")
    headers.append("#endif // UI_ICONS_H_\n")

    with open(OUT_HDR, "w") as f:
        f.write("".join(headers))

    print("wrote ui_icons.h with %d icons, PNGs in %s" % (len(meta), ICON_DIR))
    for name, w, h in meta:
        print("  %-18s %dx%d" % (name, w, h))


if __name__ == "__main__":
    main()
