#!/usr/bin/env python3
"""make_icon.py — rasterize the Material "navigation" arrow (Google-Maps style)
into a Google-blue icon with white outline, and emit:
  - assets/icon/nav_arrow.png        (RGBA preview)
  - src/ui/nav_arrow.h               (C array, RGB565, transparent = 0xF81F)

The arrow shape comes from the Material icon SVG:
  <path d="M12 2 4.5 20.29l.71.71L12 18l6.79 3 .71-.71z"/>
Polygon (24x24 box): (12,2) (4.5,20.29) (5.21,21) (12,18) (18.79,21) (19.5,20.29)
"""
from PIL import Image, ImageDraw

# ---- shape ----
PTS = [(12, 2), (4.5, 20.29), (5.21, 21.0), (12, 18), (18.79, 21.0), (19.5, 20.29)]
BOX = 24.0

# ---- render params ----
W = H = 40          # final icon size (px)
SS = 4              # supersample factor for antialiasing
GOOGLE_BLUE = (0x42, 0x85, 0xF4)   # #4285F4
OUTLINE = (255, 255, 255)
OUTLINE_W = 1.5     # px at final size

big = W * SS
scale = big / BOX
outline_px = max(1, int(round(OUTLINE_W * SS)))

img = Image.new("RGBA", (big, big), (0, 0, 0, 0))
d = ImageDraw.Draw(img)
poly = [(x * scale, y * scale) for (x, y) in PTS]
d.polygon(poly, fill=GOOGLE_BLUE + (255,), outline=OUTLINE + (255,), width=outline_px)

# smooth downscale -> antialiased edges
img = img.resize((W, H), Image.LANCZOS)

# ---------- emit C header ----------
TRANSP = 0xF81F  # magenta
def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

rows = []
for y in range(H):
    line = []
    for x in range(W):
        r, g, b, a = img.getpixel((x, y))
        line.append("0x%04X" % (TRANSP if a < 128 else rgb565(r, g, b)))
    rows.append(", ".join(line))

hdr = (
    "/* nav_arrow.h — Google-Maps-style navigation arrow, %dx%d RGB565.\n"
    " * Generated by assets/icon/make_icon.py (Material \"navigation\" icon, Apache 2.0).\n"
    " * Pixels == NAV_ARROW_TRANSP (0xF81F magenta) are transparent.\n"
    " * Arrow points NORTH (up). Rotate by -heading when drawing.\n"
    " */\n"
    "#ifndef NAV_ARROW_H\n#define NAV_ARROW_H\n\n"
    "#define NAV_ARROW_W %d\n#define NAV_ARROW_H %d\n#define NAV_ARROW_TRANSP 0xF81F\n\n"
    "static const uint16_t NAV_ARROW_PX[NAV_ARROW_W * NAV_ARROW_H] = {\n"
    % (W, H, W, H)
)
hdr += ",\n".join("    " + r for r in rows)
hdr += "\n};\n\n#endif // NAV_ARROW_H\n"

with open("/Users/tungdl/Documents/Eink/ESP32_OSM_NAV/src/ui/nav_arrow.h", "w") as f:
    f.write(hdr)
img.save("/Users/tungdl/Documents/Eink/ESP32_OSM_NAV/assets/icon/nav_arrow.png")
img.save("/Users/tungdl/Documents/Eink/ESP32_OSM_NAV/assets/icon/nav_arrow_preview_bg.png")  # replaced below

# ---------- preview on a map-ish background so it's easy to eyeball ----------
bg = Image.new("RGB", (W * 4, H * 4), (0xEA, 0xEE, 0xF2))
d2 = ImageDraw.Draw(bg)
for i in range(0, bg.width, 24):
    d2.line([(i, 0), (i, bg.height)], fill=(0xDD, 0xE3, 0xEA), width=1)
for i in range(0, bg.height, 24):
    d2.line([(0, i), (bg.width, i)], fill=(0xDD, 0xE3, 0xEA), width=1)
ic = img.resize((W * 4, H * 4), Image.NEAREST)
bg.paste(ic, ((bg.width - ic.width) // 2, (bg.height - ic.height) // 2), ic)
bg.save("/Users/tungdl/Documents/Eink/ESP32_OSM_NAV/assets/icon/nav_arrow_preview.png")

print("wrote nav_arrow.h (%d px) and nav_arrow.png %dx%d" % (W * H, W, H))
# quick stats
n = sum(1 for y in range(H) for x in range(W) if img.getpixel((x, y))[3] >= 128)
print("opaque px: %d / %d (%.0f%%)" % (n, W * H, 100.0 * n / (W * H)))
