#!/usr/bin/env python3
"""Emit src/map_tiles.h with the Bến Thành tiles as JPEG (quality 85) so the
ESP32 can show the map WITHOUT WiFi — tiles live in flash, decoded by tjpgd.
JPEG is ~3x smaller than PNG, which matters on a nearly-full 1MB partition."""
import io
import os

from PIL import Image

SRC = os.path.join(os.path.dirname(__file__), "..", "preview", "tiles")
HDR = os.path.join(os.path.dirname(__file__), "..", "src", "map_tiles.h")

TILES = [(16, 52191, 30794), (16, 52191, 30795), (16, 52192, 30794), (16, 52192, 30795)]

def cbytes(name, data):
    out = [f"static const uint8_t {name}[] = {{"]
    line = ""
    for i, b in enumerate(data):
        line += f"0x{b:02x}," if False else f"{b},"  # decimal, smaller for ccache
        if len(line) > 70:
            out.append("    " + line)
            line = ""
    if line:
        out.append("    " + line)
    out.append("};")
    return "\n".join(out)

total = 0
body = []
lookup = []
for (z, x, y) in TILES:
    fn = os.path.join(SRC, f"tile_{x}_{y}.png")
    im = Image.open(fn).convert("RGB")
    buf = io.BytesIO()
    im.save(buf, format="JPEG", quality=70, optimize=True)
    jpg = buf.getvalue()
    total += len(jpg)
    name = f"TILE_{x}_{y}"
    body.append(cbytes(name, jpg))
    lookup.append(f"    {{ {z}, {x}, {y}, {name}, sizeof({name}) }},")

with open(HDR, "w", encoding="utf-8") as f:
    f.write("""#pragma once
#include <stdint.h>
/* Embedded OSM raster tiles as JPEG (256x256) covering the Bến Thành demo
 * area at zoom 16, converted from tile.openstreetmap.org PNGs. Generated by
 * scripts/gen_embedded_tiles.py. Decoded by tjpgd — lets the monitor show a
 * real map with NO WiFi and very little flash. */

""")
    f.write("\n\n".join(body))
    f.write("\n\ntypedef struct {\n    int z, x, y;\n    const uint8_t *data;\n    uint32_t len;\n} embedded_tile_t;\n\n")
    f.write(f"static const embedded_tile_t EMBEDDED_TILES[] = {{\n{chr(10).join(lookup)}\n}};\n")
    f.write(f"#define EMBEDDED_TILES_N {len(TILES)}\n")

print(f"Generated {HDR}: {len(TILES)} JPEG tiles, {total} bytes (PNG was 109084)")
